### ISSUE TITLE
left button mouse not working :-)

### ISSUE THREAD

**Issue by dlhenke** [prograhammer/bootstrap-table-contextmenu#3]
Hello .. 
The left menu button isn't firing the context-menu..
I'm on a mac with safari and firefox.. both not working

**Comment by dlhenke** [comment]
this is my code:
var url="scripts/importar_web.php";				
	 			$('#myModal2 .modal-body').html('<table id="table"><thead><tr><th data-field="serie">DECESSO</th><th data-field="id_corretor">Corretor</th><th data-field="cod_titular">Proposta</th><th data-field="nome">Nome</th><th data-field="cpf">CPF</th></tr></thead></table>');
	 			$('#myModal2 .modal-body #table').bootstrapTable({
		 		url: url,
		 		contextMenu: '#contextMenu',
		 		contextMenuTriggerLeft: true,
		 		onContextMenuItem: function(row, $el)
		 		{
	              if($el.data("item") == "edit")
	              {
	                  alert(row.itemid);
	              }
              	}
				})
	 			$('#myModal2').modal('show');

**Comment by dlhenke** [comment]
i do not know if im right .. but .. as I need this urgently.. i put a small correction that is working for me in left mouse click ..

if(that.options.contextMenuTriggerLeft) {
             that.$body.find('> tr[data-index]').off('contextmenu').on('click', function (e) {
                var $tr = $(this);
                showContextMenu(that, $tr, e.clientX, e.clientY);
                return false;
            });
        }else{
            // Right-click context menu
            that.$body.find('> tr[data-index]').off('contextmenu').on('contextmenu', function (e) {
                var $tr = $(this);
                showContextMenu(that, $tr, e.clientX, e.clientY);
                return false;
            });
        }
        // Button-click context menu
        if (typeof that.options.contextMenuButton === 'string') {
            that.$body.find('> tr[data-index]').find(that.options.contextMenuButton).off('click').on('click', function (e) {
                var $tr = $(this).closest('tr[data-index]');
                showContextMenu(that, $tr, $(this)[0].getBoundingClientRect().left, $(this)[0].getBoundingClientRect().bottom);
                return false;
            });
        }

**Comment by dlhenke** [comment]
it is working.. but  the alert window does not arrive. :-(

**Comment by prograhammer** [comment]
Hi @dlhenke 
What do you mean by left click isn't firing the menu? The left button won't fire the context menu because it is a right click operation. The `contextmenuTriggerLeft:true` option will trigger an additional left click (after you have right clicked or clicked the context menu button) so that the row is selected. Did you see this [demo here](http://www.prograhammer.com/demos/bootstrap-table-contextmenu/)? Go to very bottom on "Trigger a Left Click" example. Where you looking to use left click to fire the menu instead?

**Comment by dlhenke** [comment]
Thank you .. and sorry i've does not analized all the code.. i was focused to solve something that the extension are not designed to do .. 
In my project i need that the left button fire the context menu. because the intranet user does not want to click the right button to open the menu.

**Comment by prograhammer** [comment]
Yeah that's why I added the ability to use a button to fire the contextmenu (good for touch devices). I'm thinking that `contextmenuTriggerLeft` is a confusing name. Let me see today, I think I can offer the ability to let you set which click fires the menu (just have to consider the left-click binding that is already in place in the parent bootstrap-table code).

**Comment by dlhenke** [comment]
I see a problem in  a button menu in all rows.. 
if you have 200 or more rows the browser becomes unresponsive .. i've tested .. thats why also the left menu is good ..  
look at this..
$('#myModal2 .modal-body #table').bootstrapTable({
                url: url,
                contextMenu: '#contextMenu',
                contextMenuTriggerLeft: true,
                contextMenuOpenOnLeftClick: true,
                onContextMenuItem: function(row, $el)
                {
                  if($el.data("item") == "edit")
                  {
                      console.log(row.nome);
                      alert(row.nome);
                  }
                  if($el.data("item") == "delete")
                  {
                      console.log(row.nome);
                      alert(row.nome);
                  }
                }
                })
.... and in your code...
 $.extend($.fn.bootstrapTable.defaults, {
        contextMenu: undefined,
        contextMenuTriggerLeft: false,
        contextMenuOpenOnLeftClick: false,
        contextMenuButton: undefined,
        onContextMenuItem: function (row, $element) {
            return false;
        },
        onContextMenuRow: function (row, $element) {
            return false;
        }
    });

..........

if(that.options.contextMenuOpenOnLeftClick) {
             that.$body.find('> tr[data-index]').off('contextmenu').on('click', function (e) {
                var $tr = $(this);
                showContextMenu(that, $tr, e.clientX, e.clientY);
                return false;
            });
        }else{
            // Right-click context menu
            that.$body.find('> tr[data-index]').off('contextmenu').on('contextmenu', function (e) {
                var $tr = $(this);
                showContextMenu(that, $tr, e.clientX, e.clientY);
                return false;
            });
        }
I do not know if is correct but is working for me.. just does not show the alert message if needed.

**Comment by prograhammer** [comment]
As soon as I get back to my PC in a bit I'll look at what you have here. It's possible the unresponsive   issue comes from looping calls from clicks triggering each other. Just my wild guess without looking yet (away from my pc).

**Comment by prograhammer** [comment]
As soon as I get back to my PC in a bit I'll look at what you have here. It's possible the unresponsive   issue comes from looping calls from clicks triggering each other. Just my wild guess without looking yet (away from my pc).

**Comment by dlhenke** [comment]
Now. i will back to work in my bass boat construction..  doing it myself in plywood and fyberglass-epoxy resin.. 
:-)

**Comment by prograhammer** [comment]
:-) That sounds awesome! It's nice to get away from the code sometimes and just do some wood-working.

**Comment by prograhammer** [comment]
Hi @dlhenke 

See the updated [readme](https://github.com/prograhammer/bootstrap-table-contextmenu/blob/master/README.md) and also the updated [demo](http://www.prograhammer.com/demos/bootstrap-table-contextmenu/). You can now use `contextMenuTrigger: 'left'` to accomplish what you need. I'm going to go ahead and reTag at v1.0.0 since I only made that version a few days ago. I also tested using a button in 200 rows and it worked good and fast. So I'm confused at what may be happening for you regarding using a button to trigger the context menu. I may have had something in the demo example code that was off, so check the demo again (now that I've updated it) and follow those examples closely. I can create a jsFiddle with 200 rows if you want.

**Comment by dlhenke** [comment]
Awesome.. 
Thank You..
